import Link from 'next/link';

export const metadata = {
  title: 'About — Signals',
  description: 'What Signals is, how it works, and why we built it.',
};

export default function AboutPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-14">
      {/* Header */}
      <div className="mb-12 pb-8 border-b border-gray-200">
        <p className="text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: '#ee7012' }}>
          About
        </p>
        <h1 className="text-4xl font-bold text-gray-900 leading-tight mb-4">
          Built for the administrator who doesn't have time.
        </h1>
        <p className="text-gray-500 text-lg leading-relaxed">
          Signals is an AI-powered intelligence platform for higher education administrators — turning
          a firehose of policy updates, research, and industry news into four focused decision briefs,
          delivered once a week.
        </p>
      </div>

      {/* Origin */}
      <section className="mb-10">
        <h2 className="text-lg font-bold text-gray-900 mb-3">Why we built this</h2>
        <div className="space-y-4 text-gray-600 leading-relaxed">
          <p>
            Academic administrators are expected to stay current on everything — ADA compliance
            updates, AI governance policies, accreditation changes, student success research — while
            also doing their actual jobs. The information exists. The time to consume it doesn't.
          </p>
          <p>
            We started experimenting with AI to solve this problem. What if you could automatically
            scan hundreds of sources, extract only the decisions and implications that matter, and
            compress them into something readable in 10 minutes? That's Signals.
          </p>
          <p>
            Every weekday, our system scans RSS feeds, policy publications, academic journals, and
            the full web. Claude — Anthropic's AI — reads each piece, extracts key signals, maps
            decision implications, and generates a structured brief. No summaries of summaries.
            Just signal.
          </p>
        </div>
      </section>

      {/* How it works */}
      <section className="mb-10 bg-gray-50 rounded-xl p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-5">How it works</h2>
        <div className="space-y-5">
          {[
            {
              step: '01',
              title: 'Ingest',
              desc: 'RSS feeds, podcasts, and Tavily web searches run automatically every weekday morning, pulling from 100+ sources across higher education.',
            },
            {
              step: '02',
              title: 'Analyze',
              desc: 'Each piece of content is read by Claude, which extracts key signals, identifies decision implications, and generates specific action items for administrators.',
            },
            {
              step: '03',
              title: 'Categorize',
              desc: 'Briefs are organized into four themes: Accessibility & Title II, AI Governance, Curriculum & Accreditation, and Student Success.',
            },
            {
              step: '04',
              title: 'Deliver',
              desc: 'A curated digest of the week\'s most important briefs lands in your inbox every Monday morning.',
            },
          ].map(({ step, title, desc }) => (
            <div key={step} className="flex gap-4">
              <span className="text-xs font-bold text-gray-300 mt-1 shrink-0 w-6">{step}</span>
              <div>
                <p className="text-sm font-semibold text-gray-900 mb-1">{title}</p>
                <p className="text-sm text-gray-500 leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* What's next */}
      <section className="mb-10">
        <h2 className="text-lg font-bold text-gray-900 mb-3">What's next</h2>
        <p className="text-gray-600 leading-relaxed">
          We're expanding source coverage, adding podcast transcription, and building toward
          personalized digests — where you choose exactly which topics and sources matter to your
          institution. If you have feedback or want to suggest a source, reach out.
        </p>
      </section>

      {/* A note on AI */}
      <section className="mb-12 border-l-4 pl-5" style={{ borderColor: '#ee7012' }}>
        <h2 className="text-sm font-bold text-gray-900 mb-2">A note on AI-generated content</h2>
        <p className="text-sm text-gray-500 leading-relaxed">
          All briefs on Signals are generated by Claude (Anthropic). We review for quality but do
          not manually edit each brief. Treat them as a first-pass intelligence layer — always verify
          critical decisions against primary sources.
        </p>
      </section>

      {/* CTA */}
      <div className="flex gap-3 flex-wrap mb-16">
        <Link
          href="/subscribe"
          className="text-sm font-bold text-white px-6 py-3 rounded transition-colors"
          style={{ backgroundColor: '#ee7012' }}
        >
          Subscribe — free
        </Link>
        <Link
          href="/newsletters"
          className="text-sm font-semibold text-gray-700 border border-gray-300 px-6 py-3 rounded hover:bg-gray-50 transition-colors"
        >
          View newsletters
        </Link>
      </div>

      {/* Author */}
      <div className="border-t border-gray-200 pt-12">
        <p className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-6">
          Built by
        </p>
        <div className="flex items-center gap-5">
          <img
            src="https://jtaolan.github.io/images/Arches.JPG"
            alt="Taolan Jiaohaer"
            className="w-16 h-16 rounded-full object-cover shrink-0"
          />
          <div>
            <Link
              href="https://jtaolan.github.io/"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-gray-900 hover:underline"
              style={{ color: '#ee7012' }}
            >
              Taolan Jiaohaer
            </Link>
            <p className="text-sm text-gray-500 mt-0.5">
              Research Assistant, Macro Lab · UCSD
            </p>
            <p className="text-sm text-gray-500 mt-1 leading-relaxed">
              Computational Social Scientist with a strong interest in the intersection of
              social science and computer science. MS in Computational Social Science, UCSD.
            </p>
            <Link
              href="https://jtaolan.github.io/"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block mt-2 text-xs font-medium hover:underline"
              style={{ color: '#ee7012' }}
            >
              jtaolan.github.io →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
